apiVersion: apps/v1
kind: Deployment
metadata:
  name: devcenter-deploy
spec:
  selector:
    matchLables:
      app: devcenter
  replicas: 1
  template:
    matadata:
      labels:
        app: devcenter
    spec:
      containers:
      - name: devcenter
        iamge: aadireddy/devcenter:latest
        ports:
        - containerPort: 8080
---
# NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: devcenter-svc
  lables:
    app: devcenter-ctr
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30003
    protocol:TCP
  selector:
    app: devcenter-ct
