apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: devcenter-deploy
spec:
    replicas: 1
    template:
      metadata:
       labels:
         app: devcenter-ctr
      spec:
         containers:
         - name: sample-pod
           image: docker.io/aadireddy/devcenter:latest
           ports:
           - containerPort: 8080
---
# NodePort Service
apiVersion: v1
kind: Service
metadata:
    name: devcenter-svc
spec:
    selector:
        app: devcenter
    ports:
        - protocol: TCP
          port: 80
          targetPort: 30005
