apiVersion: apps/v1
kind: Deployment
metadata:
  name: devcenter-deployment
  labels:
    app: devcenter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devcenter
  template:
    metadata:
      labels:
        app: devcenter
    spec:
      containers:
      - name: devcenter
        image: docker.io/aadireddy/devcenter:latest
        ports:
        - containerPort: 80
---
# NodePort Service
apiVersion: v1
kind: Service
metadata:
    name: devcenter-svc
spec:
    selector:
        app: devcenter
    ports:
        - protocol: TCP
          port: 80
          targetPort: 30005
