apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: devcenter-deploy
spec:
    replicas: 1
    template:
      metadata:
       labels:
         app: devcenter-ctr
      spec:
         containers:
         - name: sample-pod
           image: docker.io/raknas000/devcente:latest
           ports:
           - containerPort: 8080
---
# NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: devcenter-svc
  lables:
    app: devcenter-ctr
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30003
    protocol:TCP
  selector:
    app: devcenter-ct
