apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: devcenter-deploy
spec:
  replicas: 1
  template:
    matadata:
      labels:
        app: devcenter-ctr
    spec:
      containers:
      - name: devcenter-pod
        iamge: aadireddy/devcenter:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: devcenter-svc
  lables:
    app: devcenter-ctr
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30003
    protocol:TCP
  selector:
    app: devcenter-ctr  
