apiVersion: v1
kind: Service
metadata:
  name: devcenter-svc
  lables:
    app: devcenter-ctr
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30003
    protocol:TCP
  selector:
    app: devcenter-ct
